name: pymc-test-py38
channels:
- conda-forge
- defaults
dependencies:
- pymc>=4.0.0b3
- pip
- pytest-cov>=2.5
- pytest>=3.0
- python=3.9
- dask
- pip:
  - "git+https://github.com/pymc-devs/pymc.git@main"
